### ISSUE TITLE
Umdreh-Logik

### ISSUE THREAD

**Issue by LeniKoehler** [LeniKoehler/react-memory#1]
Als Memory-Liebhaber möchte ich, dass die Karten sich umdrehen.

Akzeptanzkriterien

- [x]  Beim Klicken auf eine Memory-Karte, erscheint ein anderes Bild.
- [x]  Das Umdrehen wird durch eine Function ausgelöst.

**Comment by Monogenesis** [comment]
Hab nur mal einen Prototyp fürs das "umdrehen" einer Karte auf meinem Branch implementiert.
