### ISSUE TITLE
Anreihung der Karten

### ISSUE THREAD

**Issue by LeniKoehler** [LeniKoehler/react-memory#2]
Als Memory-Spieler möchte ich, dass alle Karten in einem rechteckigen Bereich gleichmäßig aufgereiht sind, damit ich mir die Positionen besser merken kann.

Akzeptanzkriterien:

- [x]  Die Karten befinden sich alle in Reihen und Spalten.
- [x] In einer Reihe dürfen sich max. 6 Karten befinden.

**Comment by Monogenesis** [comment]
Hab hier auch mal eine Prototyplösung versucht.
